import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'dart:ui' as ui show BoxHeightStyle, BoxWidthStyle;

/// Катомный [FormBuilderTextField] использующий в качестве имени
/// Объект, приводящийся ко строке
class CustomFormBuilderTextField extends FormBuilderTextField {
  CustomFormBuilderTextField({
    super.key,
    required Object name,
    super.validator,
    super.initialValue,
    super.readOnly = false,
    super.decoration = const InputDecoration(),
    super.onChanged,
    super.valueTransformer,
    super.enabled = true,
    super.onSaved,
    super.autovalidateMode = AutovalidateMode.disabled,
    super.onReset,
    super.focusNode,
    super.maxLines = 1,
    super.obscureText = false,
    super.textCapitalization = TextCapitalization.none,
    super.scrollPadding = const EdgeInsets.all(20.0),
    super.enableInteractiveSelection = true,
    super.maxLengthEnforcement,
    super.textAlign = TextAlign.start,
    super.autofocus = false,
    super.autocorrect = true,
    super.cursorWidth = 2.0,
    super.cursorHeight,
    super.keyboardType,
    super.style,
    super.controller,
    super.textInputAction,
    super.strutStyle,
    super.textDirection,
    super.maxLength,
    super.onEditingComplete,
    super.onSubmitted,
    super.inputFormatters,
    super.cursorRadius,
    super.cursorColor,
    super.keyboardAppearance,
    super.buildCounter,
    super.expands = false,
    super.minLines,
    super.showCursor,
    super.onTap,
    super.enableSuggestions = false,
    super.textAlignVertical,
    super.dragStartBehavior = DragStartBehavior.start,
    super.scrollController,
    super.scrollPhysics,
    super.selectionWidthStyle = ui.BoxWidthStyle.tight,
    super.smartDashesType,
    super.smartQuotesType,
    super.selectionHeightStyle = ui.BoxHeightStyle.tight,
    super.autofillHints,
    super.obscuringCharacter = '•',
    super.mouseCursor,
  }) : super(name: name.toString());
}
